import { Poppins } from "next/font/google";
import "./globals.css";
import Sidenav from "@/Components/sidenav";
import Login from "../Components/Login";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const login = true;
  return (
    <html lang="en">
      {login ? (
        <body className={poppins.className}>
          <Sidenav />
          <main className=" md:ml-[300px] py-8 px-8 bg-bgColor min-h-screen">
            {children}
          </main>
        </body>
      ) : (
        <body className={poppins.className}>
          <Login />
        </body>
      )}
    </html>
  );
}
